site_name: Cloud Engineering Labs
site_author: Jon Price <jon@jonprice.io>

theme:
  name: material

edit_uri: https://github.com/mrc0der/cloud-engineering-labs/tree/main

nav:
  - AWS.md
  - Azure.md
  - CICD.md
  - Immutable.md
  - Containers.md
